### ISSUE TITLE
centralize configuration components

### ISSUE THREAD

**Issue by zmarvel** [use-adapt/adapt#4]
It's important a name like "micro-USB cable" is consistent across project configurations and the list of requirements. It might be a good idea to maintain a separate list of configuration components, such as "windows", "precision xtra", etc. to ensure consistency if anybody decides to contribute data to the project.

**Comment by jessiepusateri** [comment]
Configuration components? Would that not just be the requirements part of the json?

**Comment by zmarvel** [comment]
Sure, but maybe it needs to be explicitly stated somewhere: "For a project, the items in each `"configurations"` array come from `"requirements"`." Maybe there's even a better way to organize this information to eliminate some redundancy, but I can't put my finger on it.

**Comment by jessiepusateri** [comment]
Yeah, I can see how that might be unclear.

**Comment by jessiepusateri** [comment]
I think the response to this is https://github.com/use-adapt/configurator

**Comment by zmarvel** [comment]
Agreed @jessiepusateri
